# fourier_analysis.jl
#
# Check the frequencies generated by the network

# Move to this folder if not already there
cd(@__DIR__)
# activate the environment
using Pkg
Pkg.activate(".")

# packages
using JLD2
using Plots
using Dates
using FFTW


# read DSCM data
obs=load("DCSM-FM_0_5nm_2008_3yr_5stations_his.jld2")


# read computed tides
tides=load("tide_model_5stations_3tl_3yr_1024batch_0p0001reg_64nodes_10epochs_training_tide.jld2")

# prepare data
# measurements
obs_values=obs["waterlevel"][2,:]
obs_times=obs["times"][:]
n_obs=length(obs_values)
Δt_obs=(obs_times[2]-obs_times[1]).value/3.6e6
# tides
tide_values=tides["waterlevel"][2,:]
tide_times=tides["times"][:]
n_tide=length(tide_values)
Δt_tide=(tide_times[2]-tide_times[1]).value/3.6e6

# compute FFT 
obs_fft=fftshift(fft(obs_values))*2/n_obs
obs_freq=fftshift(fftfreq(length(obs_values), 1/Δt_obs))
tide_fft=fftshift(fft(tide_values))*2/n_tide
tide_freq=fftshift(fftfreq(length(tide_values), 1/Δt_tide))

# compute difference

# plot FFT 
p1=plot(obs_freq,abs.(obs_fft),title="FFT of observations",xlabel="frequency (1/Hrs)",ylabel="amplitude [m]",xlims=(0,0.5),label="")
p2=plot(tide_freq,abs.(tide_fft),title="FFT of tides",xlabel="frequency (1/Hrs)",ylabel="amplitude [m]",xlims=(0,0.5),label="")
plot(p1,p2,layout=(2,1),size=(800,600),legend=false)
savefig("fig_fft_tides.png")

if n_obs==n_tide
    diff_fft=obs_fft.-tide_fft
    diff_freq=obs_freq
    plot(diff_freq,abs.(diff_fft),title="FFT of difference",xlabel="frequency (1/Hrs)",ylabel="amplitude [m]",xlims=(0,0.5),label="")
    savefig("fig_fft_diff.png")
end




# test signal
# t=0.0:1.0:(n_obs-1.0)
# test_values=sin.(2π*t/24.0) + 0.5*sin.(2π*t/12.0)
# test_fft=fftshift(fft(test_values))
# test_freq=fftshift(fftfreq(length(test_values), 1/Δt_obs))
# plot(test_freq,abs.(test_fft)/n_obs,title="FFT of test signal",xlabel="frequency (1/Hrs)",ylabel="amplitude",xlims=(0,0.5),label="")