[TideSettings]
model_name = "TestTideModel"
model_dir = "models/TestTideModel"
use_gpu = true
nstations = 5
freqs = ["SSA", "K1", "O1", "Q1", "P1", "M2", "S2", "N2", "K2", "H"]

    [TideSettings.model_pars]
    nhidden_trunk = 8
    nlayers_down = 1
    nlayers_trunk = 0
    nlayers_branch = 2
    nhidden_branch = 16

[TrainingSettings]
nepochs = 2
nbatches = 1024
learning_rate = 0.001
lr_decay_factor = 0.9
lr_decay_rate = 50
weight_reg = 0.0001
patience = 10
val_daterange = ["2011-01-01T00:00:00", "2011-01-15T00:00:00"]
checkpoints = [40, 80, 120, 160]
