[WaveSettings]
model_name = "wave_model_10to11_explyr3_3stations"
model_dir = "wave_model_10to11_explyr3_3stations"
use_gpu = true
nstations = 11
nwind = 10
nlags = 16
n_input_channels = 64
wind_scale = 0.5
wave_scale = 3.0

    [WaveSettings.model_pars]
    nchannel = [64, 64, 64, 1]
    activation = "swish"

[TrainingSettings]
nepochs = 2
nbatches = 256
learning_rate = 0.001
weight_reg = 0.0001
patience = 5
input_noise_std = 0.3
